In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer , TfidfVectorizer

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../data/cleaned_data.csv")
df.head()

,review,sentiment,clean_review,tokens,label
0,One of the other reviewers has mentioned that ...,positive,one reviewer mentioned watching oz episode you...,"['one', 'reviewer', 'mentioned', 'watching', '...",1
1,A wonderful little production. <br /><br />The...,positive,wonderful little production filming technique ...,"['wonderful', 'little', 'production', 'filming...",1
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...,"['thought', 'wonderful', 'way', 'spend', 'time...",1
3,Basically there's a family where a little boy ...,negative,basically there family little boy jake think t...,"['basically', 'there', 'family', 'little', 'bo...",0
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter matteis love time money visually stunni...,"['petter', 'matteis', 'love', 'time', 'money',...",1

In [3]:
X = df.copy()
y = X["label"].values
X.drop(["label"], axis=1, inplace=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Train data:",  X_train.shape, y_train.shape)
print("Test data:",  X_test.shape, y_test.shape)

Train data: (40000, 4) (40000,)
Test data: (10000, 4) (10000,)

In [4]:
# TF-IDF
vectorizer = TfidfVectorizer(min_df=10)

X_train_tfidf = vectorizer.fit_transform(X_train["clean_review"])
X_test_tfidf = vectorizer.transform(X_test["clean_review"])

print('X_train_tfidf shape: ', X_train_tfidf.shape)
print('X_test_tfidf shape: ', X_test_tfidf.shape)

X_train_tfidf shape:  (40000, 21367)
X_test_tfidf shape:  (10000, 21367)

In [5]:
sample = X_train_tfidf[:5]

feature_names = vectorizer.get_feature_names_out()

for i, row in enumerate(sample):
    print(f"\nRow {i}:")
    
    indices = row.nonzero()[1]  
    
    for idx in indices:
        print(feature_names[idx], ":", row[0, idx])

Row 0:
thats : 0.08722238046096971
kept : 0.06391505618208328
asking : 0.07948331703035773
many : 0.10915136347028476
fight : 0.058768056576241526
screaming : 0.07979252340412686
match : 0.07294956561817191
swearing : 0.10048788216785072
general : 0.06482053201355263
mayhem : 0.09584259987870977
permeate : 0.12601373399547816
minute : 0.04433700887002388
comparison : 0.07592601131646792
also : 0.03328922266676816
stand : 0.11875763807629877
think : 0.03475553255638991
onedimensional : 0.09189062726946336
character : 0.029655681810306617
little : 0.03734776965268569
depth : 0.06871019820346459
virtually : 0.08153884545685121
impossible : 0.07029846784331911
care : 0.05454788742965214
happens : 0.05909223917469032
badly : 0.06730034741548488
written : 0.0552635502760124
cypher : 0.11634269043882713
director : 0.0830447044583485
hang : 0.08158320913994975
belief : 0.07021952920797467
topic : 0.08171715288780632
done : 0.09192918375736346
much : 0.03193079517357477
better : 0.03787433654352923
drama : 0.05662842939745485
tv : 0.04864119375417176
must : 0.1352787418882127
confess : 0.09454651226912872
im : 0.12378186251977144
not : 0.04222040933883163
really : 0.030813912644349274
one : 0.0439162018080398
spotting : 0.11688991220624725
bad : 0.03446272369811799
performance : 0.0419230971563714
film : 0.043349924778020986
said : 0.05007912702005038
heroine : 0.0790690462945663
slutty : 0.10965151102140049
best : 0.037092671583708874
friend : 0.04602352853777922
nasty : 0.07634701983585365
bullying : 0.11219532821711692
brother : 0.05744691738485029
absolutely : 0.05452870012443334
terrible : 0.05514280788862485
dont : 0.03343925709818883
know : 0.03559848499955116
acting : 0.035864315695309
school : 0.055897544638493744
graduated : 0.11141999728304222
id : 0.05722805224473552
apply : 0.10101444905869425
full : 0.05375786114823523
refund : 0.11219532821711692
post : 0.07759159825862473
lead : 0.10203175837025287
role : 0.043520883335411986
manages : 0.06763968052554165
impress : 0.08874008985121735
cast : 0.0430722890378024
socalled : 0.08673854765223302
british : 0.0646478684435022
talent : 0.05811663045921882
well : 0.0321539969856489
probably : 0.04660887953354871
never : 0.0365572201891545
hear : 0.06484728632008113
least : 0.09040115839752139
hope : 0.052918765189200634
next : 0.05342322732291636
time : 0.027183710121331386
hire : 0.08476340090852875
different : 0.049889923846267524
intriguing : 0.07616502986546021
thought : 0.043468714060167224
hideously : 0.11141999728304222
fashionable : 0.11104791212372185
soundtrack : 0.06321881993114789
featuring : 0.07817090059180754
like : 0.02476515688277871
snow : 0.0886660718177858
patrol : 0.10998772889469757
ian : 0.09107763810313617
brown : 0.080229190714749
bit : 0.045302481728297685
music : 0.0471707461071658
fan : 0.04547510421626968
familiar : 0.06892375900421924
artist : 0.07271227475282387
output : 0.10539071430024004
didnt : 0.041439563512455445
recognise : 0.10640587948326903
track : 0.07004353346274193
movie : 0.02021112333359103
apart : 0.06780421505702407
omnipresent : 0.11745947563829619
run : 0.054231493677459636
anyone : 0.04732625866717088
get : 0.059274840501590945
musical : 0.06447731552945313
montage : 0.0888893144456469
telegraph : 0.11581612354798358
suppose : 0.07290178349414497
feel : 0.04394241923592767
accompanied : 0.09170582501041977
startlingly : 0.1207189556803729
original : 0.04777587382819925
image : 0.06351991850824128
couple : 0.05285059388136761
kissing : 0.09782970067133556
lake : 0.08527495025874265
doorway : 0.11745947563829619
problem : 0.05038444262915471
none : 0.06079666662711301
song : 0.056074922651432824
convey : 0.08539122065310185
mood : 0.07092587356493697
efficiently : 0.118673490266634
realise : 0.08896452954197477
lack : 0.05586233804252455
ability : 0.06813922194506852
carry : 0.06923201095956961
emotional : 0.06631433962208616
journey : 0.07278303923205479
audience : 0.04909268334800279
storytelling : 0.08348442669091334
dialogue : 0.054503158027452134
ending : 0.04958167189091716
presumably : 0.0888893144456469
meant : 0.06765604693982814
dessert : 0.11219532821711692
everybody : 0.07328870233555809
comeuppance : 0.11805328298014521
big : 0.044931351636651046
shock : 0.07321533301707894
store : 0.06872787061441427
remained : 0.09378030748816217
resolutely : 0.12497975240153335
script : 0.04611065487672108
given : 0.052737710040849484
noone : 0.09421297367890841
root : 0.08212687661704894
enough : 0.044272506895339056
tackle : 0.09768805106301932
issue : 0.06583191534998069
actually : 0.041812189508344165
give : 0.03921537992302849
plot : 0.0364431077156727
hasnt : 0.0747887330412274
already : 0.05643659055765555
death : 0.05262573217992426
individual : 0.07465287640230284
window : 0.07569101853499309
dressing : 0.09754782509294516
noble : 0.08973986047604948
failure : 0.07749181928811719
promising : 0.08198896083268739
actress : 0.05618963956966432
mildly : 0.08328221494018999
diverting : 0.1214733213714654
save : 0.05811663045921882
bin : 0.08998111778243571
try : 0.045755139351356826
harder : 0.0903094239080984

Row 1:
character : 0.1346451247392322
not : 0.07667700669748526
really : 0.02798076360706216
one : 0.01993918908470942
dont : 0.03036472384599233
acting : 0.03256681327625936
role : 0.03951940678984196
never : 0.033196009479556754
like : 0.02248815359564258
familiar : 0.06258664486610857
movie : 0.09176417658438706
anyone : 0.04297490135241311
get : 0.026912442425994217
problem : 0.04575190417885782
lack : 0.05072614092687494
audience : 0.044578914188903765
give : 0.035609767836108044
plot : 0.033092388943535764
try : 0.041548236758348844
watch : 0.0962876515842964
entire : 0.10077182847312302
could : 0.06239058006347918
stopped : 0.07372410411967396
dvd : 0.045149782844342616
watching : 0.07343629744556952
half : 0.04871668932531238
hour : 0.04647505994899376
suggest : 0.06655025860520354
thinking : 0.05300035943230608
stop : 0.052840896623142466
taking : 0.11057782062630804
disc : 0.08215776264992607
mafia : 0.1717070883018699
tragic : 0.1382150308738157
comic : 0.0588971433776736
corky : 0.5417579116249455
romano : 0.21923918593332925
described : 0.07227988017000754
attempt : 0.09850185062423972
comedythe : 0.11179685540043247
simply : 0.04724200422400168
hard : 0.04391274907044012
laugh : 0.14014417076124547
seems : 0.040127012795852006
excuse : 0.06444232829491407
moving : 0.05735225782190233
chris : 0.20994486861572456
kattan : 0.23088330559600168
scene : 0.11922509048591023
another : 0.037942181769441294
completely : 0.04725656411751101
overplayed : 0.1022469189714868
subtlety : 0.07973386416345037
credulity : 0.10961959296666463
strange : 0.05670131846069931
mannerism : 0.0903432900923642
come : 0.034719918803843376
across : 0.05484810823959191
contrived : 0.07267083645974029
clearly : 0.056886880432727105
rather : 0.04377181019342037
bounce : 0.09505082668640538
right : 0.040637870595245415
story : 0.02772667148326177
utterly : 0.06526000119291699
predictable : 0.11400326405427207
comedic : 0.06952294716636327
event : 0.10797040938514672
occur : 0.08127348296820693
set : 0.041647654885815
obvious : 0.054311476781671655
soon : 0.05380479406009358
introduced : 0.06963606874472
comedy : 0.08502481732057769
mr : 0.05290899221464232
bean : 0.0896353108026044
disaster : 0.06905313967701349
caused : 0.07238531378213711
title : 0.04988016244856689
funny : 0.039330969862824965
empathise : 0.11261452829843538
motivation : 0.07349091595526352
initial : 0.07487293890836018
situation : 0.05351500812729222
end : 0.03338144024742763
telegraphed : 0.10470678492742072
however : 0.04098532280660157
feeling : 0.05036107200780297
deliberately : 0.08395904697150919
screwing : 0.10117561638664632
desperate : 0.07039705460136363
draw : 0.13778279753255468
played : 0.0443336520962543
alien : 0.06494225331365895
connects : 0.09927161111476107
whose : 0.055821754136368265
behaviour : 0.08595613202000822
entirely : 0.06298363397944357
inexplicable : 0.09140602928883701
except : 0.053546881182108944
trying : 0.04394636023045326
werent : 0.06374542000867138
stereotyped : 0.09189027419096699
joke : 0.05167389933384482
seemed : 0.05161896360502965
far : 0.041966660344417615
watchable : 0.06966450766262647
isnt : 0.04150806993433852

Row 2:
much : 0.06753592654588282
well : 0.06800801441914761
mood : 0.15001331978253682
moving : 0.1335866111978579
story : 0.25832720272300996
feeling : 0.11730253003648103
touching : 0.15290925441100295
love : 0.15974048005593777
reminiscent : 0.1781232712035862
drawing : 0.18737938669622295
heavily : 0.17510499597576015
chinese : 0.17390032838445915
poetry : 0.19535572406793517
used : 0.10946686047031635
eastern : 0.19835208999781895
people : 0.07131063366160781
communicate : 0.2066172484944074
focus : 0.140134018323161
schoolteacher : 0.2553292669100982
want : 0.0841777260601662
model : 0.1649713894015591
teacher : 0.1593617558823722
good : 0.05892150731831331
husband : 0.13306429211075882
father : 0.11671588255788212
senior : 0.2118192944198781
student : 0.14029107169024937
attracted : 0.18897492434648855
unfolds : 0.19435528053061005
see : 0.06242981124923302
emotion : 0.13593614794226505
surface : 0.17218079787100954
year : 0.07906828149151303
marriage : 0.1592417953187138
grapple : 0.25692480456036376
moral : 0.15527133536729842
dilemma : 0.2019407478433577
face : 0.11110737435634935
beautiful : 0.10874439225468326

Row 3:
also : 0.04226949587302683
im : 0.052391299723941694
not : 0.0268050028708962
film : 0.027522112559417052
script : 0.058549704074641565
stop : 0.07388918512545517
completely : 0.06608042704828836
comedic : 0.09721625184143508
end : 0.046678379358086955
communicate : 0.12404088592235098
student : 0.08422253682235831
face : 0.06670235543302626
latterday : 0.15328472671191462
fulci : 0.2547572684011823
totally : 0.0713202446070894
abysmal : 0.11752618940317772
concoction : 0.14579329778725245
dealing : 0.09877925258927292
gambler : 0.14054458465859088
brett : 0.13800937730150456
halsey : 0.1629674203292409
decides : 0.08783869369862779
pay : 0.08333746308069245
debt : 0.12368654952508484
seducing : 0.1396585885809561
ugliest : 0.1498999483309644
bitch : 0.12514851090173082
ever : 0.047218001661783165
lay : 0.11055057215097369
eye : 0.06721611213807822
happen : 0.07610027420204155
wealthy : 0.10777191496408091
widow : 0.11828557261897688
contrives : 0.16000785186203584
incorporate : 0.1392316708319287
element : 0.07581567002068126
result : 0.07882128389803289
unfunny : 0.10121879438491659
business : 0.0863921216613075
involving : 0.089464731358965
corpse : 0.11456662093597265
wont : 0.14309982230713814
stay : 0.07762223696494354
put : 0.059072264866062214
opera : 0.09895209522156807
singer : 0.09798052098473092
victim : 0.08346381471662788
singing : 0.09111518257607712
etc : 0.07675785922957264
mention : 0.0785035574301694
doppelganger : 0.15151162521229364
theme : 0.07552399024673613
straight : 0.08193740327452799
prague : 0.1552552255661079
although : 0.06217748530078822
case : 0.0684917514652164
two : 0.04739449474614914
persona : 0.11158287748759509
via : 0.10600561823861192
radio : 0.09835438260413693
message : 0.08018251327949837
cant : 0.054499933908516686
say : 0.04622984326679569
surprised : 0.07995815955156202
show : 0.047881215193763406
sign : 0.09441792088318468
sophistication : 0.13413502927464374
mario : 0.12201396590809185
bavas : 0.1552552255661079
hatchet : 0.14914595244355916
honeymoon : 0.1392316708319287
resembles : 0.11354816645223842
several : 0.07036093621275487
way : 0.04258034622913094
content : 0.09312182360195878
merely : 0.09549196058371595
pile : 0.10387589414655787
disgustingly : 0.1498999483309644
gory : 0.10249757653804777
effect : 0.06017089575020954
dismembered : 0.1552552255661079
limb : 0.130695316805378
squashed : 0.1574726445049495
melting : 0.1323318237248108
ala : 0.10451806831229192
become : 0.07042156379820405
associated : 0.11158287748759509

Row 4:
thats : 0.04904878290514752
many : 0.04092024319416154
think : 0.03908897147960741
character : 0.03335325386283754
better : 0.04259663863751896
not : 0.11871148671260379
really : 0.06931179377417623
one : 0.024695912185807398
bad : 0.038759654209287994
film : 0.024377470990293446
absolutely : 0.061327525352281274
know : 0.040037026122589345
cast : 0.048442689664685346
well : 0.07232613507436149
probably : 0.052420234385054255
time : 0.03057306827103354
like : 0.027852961525141762
bit : 0.050950950423784884
movie : 0.29550450103404124
get : 0.06666543077899062
emotional : 0.07458263877761093
everybody : 0.0824265889387262
actually : 0.09405095321384259
simply : 0.05851212819342649
come : 0.04300275513890463
comedy : 0.10530846631940163
funny : 0.29228295306948826
end : 0.08268993422791081
feeling : 0.06237528550454339
played : 0.10981991036785314
used : 0.05820869057980664
totally : 0.06317128418745119
ever : 0.041822932859705134
say : 0.08189536037171087
show : 0.04241036845722021
several : 0.062321585149881
first : 0.03785144875969957
firmly : 0.1082148153599393
believe : 0.05407309837174607
norwegian : 0.48623293295423664
continually : 0.10864872306420721
getting : 0.0605629372467971
tedious : 0.09140930401147301
place : 0.05323993341172987
started : 0.06873015940294919
contain : 0.09616995700542458
humour : 0.08120666443709378
imagine : 0.07256062626621665
actual : 0.07251656822473482
made : 0.11449604378054633
starting : 0.08707939513309079
entertaining : 0.062436883210591675
opposed : 0.09955608112884463
long : 0.05046864391296899
dark : 0.06468954401232596
depressing : 0.09226315917845541
great : 0.03755318261157973
new : 0.09764073109294417
generation : 0.08480420783922311
filmmaker : 0.07031704948580184
praised : 0.11321198986480022
critic : 0.07976915457842249
load : 0.0910230200022294
money : 0.05679525918062474
became : 0.07394339861825915
came : 0.05961967263621193
spoiler : 0.07378360094949521
thing : 0.03820482466582262
especially : 0.054287342451187805
comedian : 0.09145826503548687
neither : 0.07807166448183736
anything : 0.05195453853672207
wheres : 0.10909497101632103
humor : 0.12971934575281413
awkward : 0.08872035109806962
clerk : 0.10971042226929782
overacting : 0.10129177073161373
ridiculously : 0.10031348260930462
unrealistic : 0.09027785945048537
football : 0.09584234603592412
coach : 0.10101885958383225
commentary : 0.08522702293329794
main : 0.05576368468274235
rant : 0.112824513499987
united : 0.09180533753524579
namely : 0.10283332788014914
predictability : 0.12295399678584716
fear : 0.07642670789478981
since : 0.05248965907159977
seen : 0.04002222584281634
going : 0.04712111562314558
exactly : 0.1361515227806599
presented : 0.08209909192914125
start : 0.052925402929151634
deserve : 0.08586622794729776
there : 0.05373273352821794
room : 0.06980292294515679
surprise : 0.07021540057673355
sat : 0.08583192849000008
seeing : 0.05647016291297983
realize : 0.07478468442897099
need : 0.05396931197019453
blood : 0.06932902876414059
making : 0.053429984675241245

In [6]:
row = X_train_tfidf[0]

indices = row.nonzero()[1]

sorted_data = sorted(
[(feature_names[i], row[0, i]) for i in indices],
key=lambda x: x[1],
reverse=True
)

sorted_data[:10]

[('must', np.float64(0.1352787418882127)),
 ('permeate', np.float64(0.12601373399547816)),
 ('resolutely', np.float64(0.12497975240153335)),
 ('im', np.float64(0.12378186251977144)),
 ('diverting', np.float64(0.1214733213714654)),
 ('startlingly', np.float64(0.1207189556803729)),
 ('stand', np.float64(0.11875763807629877)),
 ('efficiently', np.float64(0.118673490266634)),
 ('comeuppance', np.float64(0.11805328298014521)),
 ('omnipresent', np.float64(0.11745947563829619))]

In [7]:
import pandas as pd

sample = X_train_tfidf[:10]
feature_names = vectorizer.get_feature_names_out()

rows_list = []

for i in range(sample.shape[0]):
    row = sample[i]
    indices = row.nonzero()[1]

    row_data = {'Row': i}

    for idx in indices:
        row_data[feature_names[idx]] = row[0, idx]

    rows_list.append(row_data)

df_nonzero = pd.DataFrame(rows_list)

df_nonzero.fillna('', inplace=True)

df_nonzero

C:\Users\Workstation\AppData\Local\Temp\ipykernel_17060\434302225.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_nonzero.fillna('', inplace=True)

,Row,thats,kept,asking,many,fight,screaming,match,swearing,general,...,lost,spent,million,location,impressive,told,nothing,promoted,period,human
0,0,0.087222,0.063915,0.079483,0.109151,0.058768,0.079793,0.07295,0.100488,0.064821,...,,,,,,,,,,
1,1,,,,,,,,,,...,,,,,,,,,,
2,2,,,,,,,,,,...,,,,,,,,,,
3,3,,,,,,,,,,...,,,,,,,,,,
4,4,0.049049,,,0.04092,,,,,,...,,,,,,,,,,
5,5,,,,0.060895,,,,,,...,,,,,,,,,,
6,6,,,,,,,,,,...,,,,,,,,,,
7,7,,,,0.03651,0.058972,,,,,...,,,,,,,,,,
8,8,,,,,,,,,,...,,,,,,,,,,
9,9,,,,0.072635,,,,,,...,0.037235,0.044669,0.046701,0.044011,0.046846,0.039733,0.028023,0.066313,0.043179,0.036138

In [8]:
from scipy.sparse import save_npz
X_test.to_csv("../outputs/X_test_reviews.csv", index=False)
# Save TF-IDF sparse matrices
save_npz("../outputs/X_train_tfidf.npz", X_train_tfidf)

save_npz("../outputs/X_test_tfidf.npz", X_test_tfidf)

# Save labels
np.save("../outputs/y_train.npy", y_train)

np.save("../outputs/y_test.npy", y_test)

In [9]:
import joblib

# Save TF-IDF vectorizer
joblib.dump(
    vectorizer,
    '../outputs/tfidf_vectorizer.pkl'
)

['../outputs/tfidf_vectorizer.pkl']