In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer , TfidfVectorizer

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(r"D:\information\cleaned_data.csv")
df.head()

,review,sentiment,clean_review,tokens,label
0,One of the other reviewers has mentioned that ...,positive,one reviewer mentioned watching oz episode you...,"['one', 'reviewer', 'mentioned', 'watching', '...",1
1,A wonderful little production. <br /><br />The...,positive,wonderful little production filming technique ...,"['wonderful', 'little', 'production', 'filming...",1
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...,"['thought', 'wonderful', 'way', 'spend', 'time...",1
3,Basically there's a family where a little boy ...,negative,basically there family little boy jake think t...,"['basically', 'there', 'family', 'little', 'bo...",0
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter matteis love time money visually stunni...,"['petter', 'matteis', 'love', 'time', 'money',...",1

In [3]:
# df.drop(["review", "sentiment","clean_review"], axis=1, inplace=True)

In [4]:
df.head()

,review,sentiment,clean_review,tokens,label
0,One of the other reviewers has mentioned that ...,positive,one reviewer mentioned watching oz episode you...,"['one', 'reviewer', 'mentioned', 'watching', '...",1
1,A wonderful little production. <br /><br />The...,positive,wonderful little production filming technique ...,"['wonderful', 'little', 'production', 'filming...",1
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...,"['thought', 'wonderful', 'way', 'spend', 'time...",1
3,Basically there's a family where a little boy ...,negative,basically there family little boy jake think t...,"['basically', 'there', 'family', 'little', 'bo...",0
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter matteis love time money visually stunni...,"['petter', 'matteis', 'love', 'time', 'money',...",1

In [10]:
X = df["clean_review"]
y = df["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# TF-IDF
vectorizer = TfidfVectorizer(max_features=5000)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [ ]:
# sample the data
sample = X_train_tfidf[:].toarray()

# names feature
feature_names = vectorizer.get_feature_names_out()

# convert ro datframe
df_sample = pd.DataFrame(sample, columns=feature_names)

# first number of rows
df_sample.iloc[:, :1000]

,aaron,abandoned,abc,ability,able,absence,absent,absolute,absolutely,absurd,...,cow,cowboy,cox,crack,craft,crafted,craig,crap,crappy,crash
0,0.0,0.0,0.0,0.082503,0.0,0.0,0.0,0.000000,0.066023,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.072129,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,0.0,0.0,0.0,0.186175,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39996,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39997,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.175506,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39998,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.152258,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39999,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0