In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer , TfidfVectorizer

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../data/cleaned_data.csv")
df.head()

,review,sentiment,clean_review,tokens,label
0,One of the other reviewers has mentioned that ...,positive,one reviewer mentioned watching oz episode you...,"['one', 'reviewer', 'mentioned', 'watching', '...",1
1,A wonderful little production. <br /><br />The...,positive,wonderful little production filming technique ...,"['wonderful', 'little', 'production', 'filming...",1
2,I thought this was a wonderful way to spend ti...,positive,thought wonderful way spend time hot summer we...,"['thought', 'wonderful', 'way', 'spend', 'time...",1
3,Basically there's a family where a little boy ...,negative,basically there family little boy jake think t...,"['basically', 'there', 'family', 'little', 'bo...",0
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,petter matteis love time money visually stunni...,"['petter', 'matteis', 'love', 'time', 'money',...",1

In [3]:
X = df.copy()
y = X["label"].values
X.drop(["label"], axis=1, inplace=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Train data:",  X_train.shape, y_train.shape)
print("Test data:",  X_test.shape, y_test.shape)

Train data: (40000, 4) (40000,)
Test data: (10000, 4) (10000,)

In [4]:
# TF-IDF
vectorizer = TfidfVectorizer(min_df=10)

X_train_tfidf = vectorizer.fit_transform(X_train["clean_review"])
X_test_tfidf = vectorizer.transform(X_test["clean_review"])

print('X_train_tfidf shape: ', X_train_tfidf.shape)
print('X_test_tfidf shape: ', X_test_tfidf.shape)

X_train_tfidf shape:  (40000, 21367)
X_test_tfidf shape:  (10000, 21367)

In [6]:
# sample the data
sample = X_train_tfidf[:100].toarray()

# names feature
feature_names = vectorizer.get_feature_names_out()

# convert ro datframe
df_sample = pd.DataFrame(sample, columns=feature_names)

# first number of rows
df_sample.iloc[:, :1000]

,aa,aag,aaliyah,aamir,aardman,aaron,ab,aback,abandon,abandoned,...,army,arnie,arnold,around,aroundthe,arouse,aroused,arousing,arquette,arquettes
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
from scipy.sparse import save_npz
X_test.to_csv("../outputs/X_test_reviews.csv", index=False)
# Save TF-IDF sparse matrices
save_npz("../outputs/X_train_tfidf.npz", X_train_tfidf)

save_npz("../outputs/X_test_tfidf.npz", X_test_tfidf)

# Save labels
np.save("../outputs/y_train.npy", y_train)

np.save("../outputs/y_test.npy", y_test)

In [10]:
import joblib

# Save TF-IDF vectorizer
joblib.dump(
    vectorizer,
    '../outputs/tfidf_vectorizer.pkl'
)

['../outputs/tfidf_vectorizer.pkl']